# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0011_contentnode_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='source_url',
        ),
        migrations.AddField(
            model_name='file',
            name='source_url',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
